### ISSUE TITLE
Refactor SECVISOGRAM_VERSION

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#144]
Secvisogram uses the GitRevisionPlugin to generate its version string (`SECVISOGRAM_VERSION`). This is used in multiple places: see [here](https://github.com/search?q=SECVISOGRAM_VERSION+repo%3Asecvisogram%2Fsecvisogram&type=Code&ref=advsearch&l=&l=) The current status was introduced with 7448d2988bbed850678aeedae75954945aa4949a

It is used for the following purposes:

* Version string in the upper right corner of Secvisogram
* Version string as value for `/document/tracking/generator/engine/version`
* Version string for the tests

The following code is defined twice:
* https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/SecvisogramPage/View/Reducer.js#L5-L12
* https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/shared/Core.js#L13-L20

This violates the DRY principle and should be fixed. 

It should also be considered to extract the generator setting in 
https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/shared/Core.js#L22-L27

and its sibling https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/SecvisogramPage/View/Reducer.js#L49-L53

so that there is a single place to update that.

**Comment by bentolor** [comment]
@domachine We should update [our architecture documentation & diagram](https://github.com/secvisogram/secvisogram/blob/main/DEVELOPMENT.md#secvisogram-architecture--design) in case we want to introduce a central (lookup) place for common business functionality reuse.
