### ISSUE TITLE
BCP Validation implementation

### ISSUE THREAD

**Issue by bentolor** [secvisogram/secvisogram#200]
This issue is related around specification section "6.1.12 Language" https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md#6112-language

The [current state of implementation](https://github.com/exxcellent/secvisogram/blob/feature/mandatory-tests-4/app/lib/shared/bcpLanguageTagChecker.js) uses the `bcp47` library to parse a BCP string and then checks in [`bcpLanguageTagChecker.js `](https://github.com/exxcellent/secvisogram/blob/feature/mandatory-tests-4/app/lib/shared/bcpLanguageTagChecker.js) that the subtags can be found with expected `Type:` entries in the subtag registry. This is what we understood so far.

@tschmidtb51 mentioned the following examples:

> Examples for vlaid tags aa-DE, sjo-Sora-AN , sry-Visp-, tig-x-Y, eo-arkaika, de-1996, i-DeFaULt
> Examples for invalid tags: ez, abx-i-mingo, ads-aeb

The implementation accepts all valid tags, but it also accepts `abx-i-mingo` and `ads-aeb`.

As far as I understood:
* `abx-i-mingo` is a valid BCP tag, but illegal to a grandfathered tag; For Secvisogram it's *okay* to report is as valid according to BCP, as the regex already marks it as invalid. Right?
* The issue with `ads-aeb` is more difficult to grasp for us and I'm not sure why it should be invalid within the scope of our original check requirements (see below).

#### Case  `ads-aeb` 

This is listed in the registry as language, but also as extension:
```
Type: extlang
Subtag: aeb
Description: Tunisian Arabic
Added: 2009-07-29
Preferred-Value: aeb
Prefix: ar
Macrolanguage: ar
```

Given that `ads` is the language,  the position of `aeb` seems perfectly reasonable to me as extension. Also `aeb` is a valid `extlang` subtag. 

I only see a violation of `Prefix: ar` vs. the actual language being `aeb`. 

Besides checking, that
> every parsed subtag can be found in the subtag registry list under a Type which allows the given position in the language string

should we also additionally check for this requirement?

CC @domachine

**Comment by sthagen** [comment]
Well, the CSD01 only stated:
> For each element of type /$defs/language_t it must be tested that the language code is valid and exists.

When it comes to programmatic handling the details of languages, calendars, and time zones across interfaces I rather suggest following Postel's Law, also known as the robustness principle, which states:

> Be conservative in what you do, be liberal in what you accept from others.
> (Postel wrote this in an early version of the TCP specification in 1980 thus the name stuck somehow)

**Comment by tschmidtb51** [comment]
>     * The issue with `ads-aeb` is more difficult to grasp for us and I'm not sure why it should be invalid within the scope of our original check requirements (see below).

As far as I understand [BCP 47 Section 2.2.2](https://www.ietf.org/rfc/bcp/bcp47.txt) an `extlang` subtag can not exist in any other `language` as given by `prefix`. The prefix value of `aeb` is `ar`. Therefore, it can as an `extlang` only exist as `ar-aeb`. Does that make sense?

**Comment by tschmidtb51** [comment]
@domachine: I found another one :see_no_evil:: `az-baku1926` should be valid. However, according to Secvisogram #218 it is not.  The problem is that the Prefix should be an array where only one of them has to match as the [registry](https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry) lists:
```
%%
Type: variant
Subtag: baku1926
Description: Unified Turkic Latin Alphabet (Historical)
Added: 2007-04-18
Prefix: az
Prefix: ba
Prefix: crh
Prefix: kk
Prefix: krc
Prefix: ky
Prefix: sah
Prefix: tk
Prefix: tt
Prefix: uz
```
As `uz-baku1926` works, I guess we take only the last one during parsing...
