### ISSUE TITLE
Randomized port

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#213]
It looks like the port is now randomized once you run `npm run dev` without mentioning a dedicated port. Also it binds to the network and not only localhost.

@sthagen, @pdamian, @mfd2007 : Can anyone confirm that? Or is it just on my machine?

**Comment by mfd2007** [comment]
I can't confirm this problem. If I start `npm run dev`, I get the information about the binding of the server:

> <i> [webpack-dev-server] Project is running at:
<i> [webpack-dev-server] Loopback: http://localhost:42405/
<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.XXX.XXX:42405/

**Comment by sthagen** [comment]
I will try - have a pending issue report, as with my lts node and matching npm I could not even install from the fork anymore  (but have no access to details until later)

**Comment by tschmidtb51** [comment]
> I can't confirm this problem. If I start `npm run dev`, I get the information about the binding of the server:

Well, I guess my problem description was incomplete: Before something* (I haven't figured out that and to exclude that it is just on my machine I called for help...) changed, the server started default at port 8080 (as documented in the Readme).
It looks basically the same for me, as @mfd2007 quoted:

> > [webpack-dev-server] Project is running at:
> >  [webpack-dev-server] Loopback: http://localhost:42405/
> >  [webpack-dev-server] On Your Network (IPv4): http://192.168.XXX.XXX:42405/

The port changes whenever you restart the dev server (and therefore seems to be randomized).

@mfd2007: Which version of node & npm do you run?
```
  $ node --version ; npm --version
 ```

**Comment by mfd2007** [comment]
```
node --version ; npm --version
v14.18.2
6.14.15
```

**Comment by sthagen** [comment]
@tschmidtb51 I can confirm the randomized ports now occuring with the current LTS configuration of node. (The workaround in [#214](https://github.com/secvisogram/secvisogram/issues/214#issuecomment-996001747).

Run no. 1:
```diff
❯ npm run dev

> dev
> cd app && npm run dev


> dev
> webpack serve --mode development --port=$npm_config_port

<i> [webpack-dev-server] Project is running at:
+<i> [webpack-dev-server] Loopback: http://localhost:60181/
+<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.118:60181/
# ...
```

Run no. 2:

```diff
❯ npm run dev

> dev
> cd app && npm run dev


> dev
> webpack serve --mode development --port=$npm_config_port

<i> [webpack-dev-server] Project is running at:
-<i> [webpack-dev-server] Loopback: http://localhost:60219/
-<i> [webpack-dev-server] On Your Network (IPv4): http://192.168.1.118:60219/
# ...
```

**Comment by tschmidtb51** [comment]
Preferred solution: default start on 8080, but it is possible to override the default port when using `--port=` on the command line
