### ISSUE TITLE
Reduction of current release and intital release time

### ISSUE THREAD

**Issue by MimounMen** [secvisogram/secvisogram#230]
When filling in the Timestamps into the form. The resulting CSAF Document reduce the given timestamp by 1 hour.
<img width="498" alt="editor" src="https://user-images.githubusercontent.com/62646829/152346068-bb0b93f0-5dfe-4942-944d-f8e58254c705.png">
<img width="517" alt="form" src="https://user-images.githubusercontent.com/62646829/152346080-d363536c-7aff-46fc-87ee-dc70f1bf2b17.png">

**Comment by sthagen** [comment]
Guessing: the entry form is assuming local time CET maybe which would match the zulu time in the resulting data and in summer that would be two and in the  ET time zone e.g. it would transform a few hours ahead.

**Comment by MimounMen** [comment]
I also got the Case with the 2 Hour difference.
I got confused, since there is only a change of the time stamp without any time Zone Field, which would  indicate a transformation.
I get it now.
