### ISSUE TITLE
Vulnerability-ID not allowed anymore?

### ISSUE THREAD

**Issue by pixelkunst-net** [secvisogram/secvisogram#256]
Just re-visited to align an implementation with Secvisogram. Maybe the adaption of the CSAF validation library has issues?

When I copy&paste a CSAF security_advisory (which also seems to have been renamed to csaf_security_advisory) document, that holds the [vulnerabilities[]/id](https://docs.oasis-open.org/csaf/csaf/v2.0/cs01/csaf-v2.0-cs01.html#61278-vulnerability-id) section (in case where no CVE is available), this creates an error message `[/vulnerabilities/0: must NOT have additional properties](https://secvisogram.github.io/#/vulnerabilities/0)`.

Is this an error in Secvisogram or will the specification change in this part?

**Comment by tschmidtb51** [comment]
@pixelkunst-net The specification changed that part with [CSD02](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md#3236-vulnerabilities-property---ids). It is now called `ids` and is an array. Secvisogram already implements CSD02.

**Comment by tschmidtb51** [comment]
I guess that can be closed, right?

**Comment by pixelkunst-net** [comment]
Thanks for the clarification, I'll close this issue now.
