### ISSUE TITLE
Feature request load from URL

### ISSUE THREAD

**Issue by sei-vsarvepalli** [secvisogram/secvisogram#313]
Is it possible to provide a way to load CSAF data from a URL instead of a local file? The use case is more of a presentation use case where a published CSAF document can be loaded for updates, reviews and changes. For example a CSAF feed or CSAF individual document location https://kb.cert.org/vuls/api/309662/csaf/ can be loaded into secvisogram.

Vijay

**Comment by tschmidtb51** [comment]
I'm not sure yet - as we are working on the [backend](https://github.com/secvisogram/csaf-cms-backend) there might be a way to do that. I guess, we will defer that until we have Secvisogram 2.0 published.

**Comment by tschmidtb51** [comment]
I suggest to add an additional option "Load from URL" into the opening dialogue. Please also check if the security considerations need to be updated when adding this change.

**Comment by MarcoKorinth** [comment]
This could create problems with cors-policies.
Loading from URL would therefore only work with servers, which listed the secvisogram url in its cors-policy.
One easy solution would be to just display an error message for cors-errors. Otherwise it would also be possible to use a backend proxy.
Which one would you prefer?

**Comment by mfd2007** [comment]
yes, an error message about the reason is necessary. It would also be easier if no backend was necessary. 
We can try it out.

I would suggest an additional option in the "New" dialog.

**Comment by MarcoKorinth** [comment]
Sounds good!

**Comment by StefanNemeth** [comment]
Released in new version 2.2.0
