### ISSUE TITLE
JSON monaco editor: validation of document/category

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/secvisogram#317]
If I choosing the option "csaf_security_advisory" or "csaf_vex", the following hint is shown: "reserved prefix used". That's not the case for "csaf_base" and should not for the first two cases either.

This happens, when I choose "csaf_base" first, then change some values in the document and then change the category to one of the two values.

Problem is solved, when I switch to Form-Editor and then back to JSON-Editor.

**Comment by tschmidtb51** [comment]
The same happens with `csaf_informational_advisory` and `csaf_security_incident_response`.

It happens only when the value is typed, not when it is copied into the field. I could reproduce it when I use a new minimal document, but nor with a complete one.
