### ISSUE TITLE
Update CWE list

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#340]
Currently, the CWE list used for the suggest feature in the form editor is outdated. Shouldn't that be part of the csaf-validator-lib? To test, use `CWE-1244`:
- The suggestion provides `Improper Access to Sensitive Information Using Debug and Test Interfaces` while the validator marks that as incorrect. (Correct would be `Internal Asset Exposed to Unsafe Debug Access Level or State` see also [CWE-1244](https://cwe.mitre.org/data/definitions/1244.html)).

**Comment by tschmidtb51** [comment]
@domachine Shouldn't that be loaded from the csaf-validator-lib?

**Comment by tschmidtb51** [comment]
As discussed in today's meeting: This is not done yet, but should be implemented with CR2.

**Comment by italvi** [comment]
Same can be observed for CWE-1059:
![image](https://user-images.githubusercontent.com/58322186/204221723-c47db7c7-a934-434e-9e86-1f870b1c160a.png)

**Comment by mfd2007** [comment]
There are two different lists with CWE-Informations. An old version 4.3 in 

- [secvisogram/app/lib/app/shared/Core/cwec_4.3.json](https://github.com/secvisogram/secvisogram/blob/feat/wizzard/app/lib/app/shared/Core/cwec_4.3.json) 
- [secvisogram/data/cwec_v4.3.xml ](https://github.com/secvisogram/secvisogram/blob/feat/wizzard/data/cwec_v4.3.xml)

The new version 4.9 can be found [here](https://cwe.mitre.org/data/xml/cwec_latest.xml.zip)

CSAF validator lib seems to use the correct version in  [secvisogram/csaf-validator-lib/lib/shared/cwec.js](https://github.com/secvisogram/secvisogram/blob/feat/wizzard/csaf-validator-lib/lib/shared/cwec.js).

This also results in the "wizzard" to an error, if you try the CWE mentioned above.
