### ISSUE TITLE
Implement validation mandatory tests

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#36]
This issue tracks the progress to update Secvisogram to implement the tests required by the schema (see [6.1 Mandatory Tests](https://github.com/oasis-tcs/csaf/blob/master/csaf_2.0/prose/csaf-v2-editor-draft.md#61-mandatory-tests)):

**Error:**
- [ ] 6.1.1 Missing Definition of Product ID
- [ ] 6.1.2 Multiple Definition of Product ID
- [ ] 6.1.3 Circular Definition of Product ID
- [ ] 6.1.4 Missing Definition of Product Group ID
- [ ] 6.1.5 Multiple Definition of Product Group ID
- [ ] 6.1.6 Contradicting Product Status
- [ ] 6.1.7 Multiple Scores with same Version per Product
- [ ] 6.1.8 Invalid CVSS
- [ ] 6.1.9 Invalid CVSS computation
- [ ] 6.1.10 Inconsistent CVSS
- [ ] 6.1.11 CWE
- [ ] 6.1.12 Language
- [ ] 6.1.13 PURL
- [ ] 6.1.14 Sorted Revision History
- [ ] 6.1.15 Translator
- [ ] 6.1.16 Latest Document Version
- [ ] 6.1.17 Document Status Draft
- [ ] 6.1.18 Released Revision History
- [ ] 6.1.19 Revision History Entries for Pre-release Versions
- [ ] 6.1.20 Non-draft Document Version
- [ ] 6.1.21 Missing Item in Revision History
- [ ] 6.1.22 Multiple Definition in Revision History
- [ ] 6.1.23 Multiple Use of Same CVE
- [ ] 6.1.24 Multiple Definition in Involvements
- [ ] 6.1.25 Multiple Use of Same Hash Algorithm
- [ ] 6.1.26 Prohibited Document Category Name
- [ ] 6.1.27 Profile Tests
  - [ ] 6.1.27.1 Document Notes
  - [ ] 6.1.27.2 Document References
  - [ ] 6.1.27.3 Vulnerabilities
  - [ ] 6.1.27.4 Product Tree
  - [ ] 6.1.27.5 Vulnerability Notes
  - [ ] 6.1.27.6 Product Status
  - [ ] 6.1.27.7 VEX Product Status
  - [ ] 6.1.27.8 Vulnerability ID
  - [ ] 6.1.27.9 Impact Statement
  - [ ] 6.1.27.10 Action Statement

Some of these tests are already implemented. All should be tested with the files given in the standard.

**Option:** Implement them in way that the checks can also be performed from the console.

**Comment by domachine** [comment]
@tschmidtb51 I guess this ticket can be closed.

**Comment by tschmidtb51** [comment]
All mandatory tests from CS01 have been implemented in Secvisogram 1.11.0.
