### ISSUE TITLE
feat/wizzard: Problem with relevance level for CSAF Advisories

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/secvisogram#376]
Version: [v2.0.0-230-g694c4d7]

If you choose "csaf_security_advisory" and relevance level "1", 

- there is no possibility to create products.
- there is no possibility to create a product status in vulnerabilities/vul1/product_status

![grafik](https://user-images.githubusercontent.com/58845044/209918876-4dc06fd8-4c2f-4b8d-9781-c860fc3555fa.png)

Therefore no valid document can be generated.

The name of the vulnerability can alo not be changed, that would be helpful.

**Comment by valentindey** [comment]
This actually works as designed. The relevance level of `product_status` is set to `mandatory` for the selected profile and is correctly shown. All lists of product ids below have a lesser relevance level and thus are not shown.

If the assigned relevance levels are incorrect, you could adjust these by editing `app/scripts/importUIMetaData/metaData.js` and running the script `importUIMetaData.js`.

**Comment by tschmidtb51** [comment]
@valentindey is right: It works as designed.
The spec lists `/product_tree` as mandatory but doesn't specify how the products MUST be organized. (However, the schema enforces that at least one element exists.) So this is a gap in the definition that can only be solve by activating the next relevance level (to be consistent)...
