### ISSUE TITLE
feat/wizzard: Validation problem after deleting last element of list

### ISSUE THREAD

**Issue by mfd2007** [secvisogram/secvisogram#377]
Version: v2.0.0-230-g694c4d7

If you create (valid) product groups and then delete the last one, the validation shows the error, that `/product_tree/product_groups: must NOT have fewer than 1 items`. 

![grafik](https://user-images.githubusercontent.com/58845044/209926218-732a37aa-b4e1-4797-9a0b-f1e7e4c1d70f.png)

In the json `"product_groups": []` is still there. 

When deleting items, I would expect a check, if the element is empty and then drop it from the internal representation. The Problem is relevant on all lists.

**Comment by valentindey** [comment]
should be fixed with https://github.com/secvisogram/secvisogram/pull/386
