### ISSUE TITLE
feat/wizzard: Missing generation of  "Full Product Name" 

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#394]
The generation of the  "Full Product Name" is currently not available (but was in Form Editor). (Could be done via button).

**Comment by valentindey** [comment]
Can you please clarify what exactly is generated and how that was done in the previous version?

**Comment by tschmidtb51** [comment]
The [current version online](https://secvisogram.github.io/) takes
- for a leaf of `branches` all values of `name` along the path an concatenates them (https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/SecvisogramPage/View/FormEditorTab/shared/definitions/Branches.js)
- for a `relationship` concatenates the (resolved) values of `product_reference` `category` `relates_to_product_reference`. The `category` is used with `_`. (https://github.com/secvisogram/secvisogram/blob/8f995ab39e983d4542c6ddca9f478548a525d61e/app/lib/SecvisogramPage/View/FormEditorTab/ProductTree.js)

I think the automatic generation might be hard / inaccurate - so a button would be fine. That should delete the current content and set the newly generated one.

**Comment by valentindey** [comment]
should be fixed in https://github.com/secvisogram/secvisogram/pull/409
