### ISSUE TITLE
feat/wizzard: Automatic assignment of Product_ids missing

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#395]
The automatic assignment of `product_id` doesn't work currently.

**Comment by valentindey** [comment]
Should be fixed in https://github.com/secvisogram/secvisogram/pull/404

**Comment by tschmidtb51** [comment]
You are correct - the one for `group_ids` is missing as well. (I though I opened a separate issue for that but it must have slipped through).

**Comment by tschmidtb51** [comment]
Merged #404

**Comment by tschmidtb51** [comment]
The reset actually doesn't work when creating a new document with the "New" Button. (tested in #409 )

**Comment by valentindey** [comment]
The reset of ID counters for new documents should be fixed in https://github.com/secvisogram/secvisogram/pull/411
