### ISSUE TITLE
feat/wizzard: Fields of `remeditation` are behind the sidebar

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#396]
The fields of `remeditation` are behind the sidebar.

**Comment by tschmidtb51** [comment]
It seems to be even worse for items of `group_ids`.

**Comment by tschmidtb51** [comment]
Maybe, this could be solved by putting the items of vulnerabilities in the left column?

**Comment by valentindey** [comment]
This will be the case for any field that is deeply nested in the tree. Tweaking this for individual cases does not feel very sustainable.
Once the space on your screen is not sufficient anymore, you are able to scroll horizontally, though.

**Comment by tschmidtb51** [comment]
> Please let us know if the scrolling resolves your problem.

I'm currently not 100% happy with the suggestion, as putting items of vulnerabilities below `Vulnerabilities` seems to improve the situation for many deeply nested items...

**Comment by cloeser** [comment]
This is currently not possible. Object menus and lists are two different components. Adding list items below menu items would require a lot of changes.

Some thoughts:
Displaying every list item below the corresponding menu item would also lead to quite long vertical lists.
Displaying only one or some lists below menu items could (IMHO) be confusing for the user.

**Comment by tschmidtb51** [comment]
> This is currently not possible. Object menus and lists are two different components. Adding list items below menu items would require a lot of changes.

In this case, I suggest to leave it as is for now.
