### ISSUE TITLE
feat/wizzard: Inconsistent naming

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#406]
- In `branches` the value of `name` is used => intended.
- In `full_product_names` the `product_id` is used => should be `name`
- In `product_groups` the `group_id` is used => should be `summary` (@mfd2007 correct?)
- In `relationships` the `Relationship i` is used => should be `full_product_name/name` (@mfd2007 correct?)

I might be mistaken here - need to double check with @mfd2007

**Comment by valentindey** [comment]
If I understand correctly, you're referring to what's displayed as name for an item in a list.

I changed that in https://github.com/secvisogram/secvisogram/pull/407

You can easily adjust that to your liking by changing the `itemNameField` property in `metaData.json`. See the corresponding [Readme](https://github.com/secvisogram/secvisogram/blob/feat/wizzard/app/scripts/importUiMetaData/README.md) for details. Don't forget to run the importUiMetaData.js script after the changes.

However, the last case of `relationships` you mention using a nested field currently won't work and would require quite some additional work.

**Comment by tschmidtb51** [comment]
> If I understand correctly, you're referring to what's displayed as name for an item in a list.

Yes.

> I changed that in #407

You were so fast that I didn't had a chance to discuss that with @mfd2007 before. But the PR looks good to me...

I assigned the topic to @mfd2007 - he will provide his thoughts.

**Comment by tschmidtb51** [comment]
As discussed:
- In `product_groups` the `group_id` is used and should be used as `summary` can be quite lengthy

**Comment by tschmidtb51** [comment]
Same applies for `releationships` - we keep the current implementation for now....
