### ISSUE TITLE
feat/wizzard: Update to latest csaf-validator-lib

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#410]
This is just a reminder to update to the latest version of the csaf-validator-lib and update the dependencies before merging `feat/wizzard` into `main`.

**Comment by valentindey** [comment]
updated in https://github.com/secvisogram/secvisogram/pull/415

**Comment by valentindey** [comment]
for the sake of completeness: dependencies have been updated in https://github.com/secvisogram/secvisogram/pull/418
