### ISSUE TITLE
feat/wizard: rendered preview not scrollable anymore

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#424]
During the test of `feat/wizard` I realized that the rendered preview is not scrollable anymore.

**Steps to reproduce:**
- Start Secvisogram.
- Open an existing advisory (or paste one into the JSON editor) - e.g. [wid-sec-w-2022-0004](https://wid.cert-bund.de/.well-known/csaf/white/2022/wid-sec-w-2022-0004.json)
- Go to the Preview tab

**Expected behavior: ** It should be possible to scroll down.

**Actual behavior:** Scrollbar disappears - scroll is impossible. *Note: Scrolling still works for the HTML Source.*

**Comment by valentinkoe** [comment]
should be fixed in https://github.com/secvisogram/secvisogram/pull/425

**Comment by tschmidtb51** [comment]
> should be fixed in #425

@valentinkoe, @cloeser Please see my comment in https://github.com/secvisogram/secvisogram/pull/425#pullrequestreview-1336515231 (Happy to discuss over phone...)
