### ISSUE TITLE
Incorrect REST pathnames when using csaf-cms-backend

### ISSUE THREAD

**Issue by ljaenicke** [secvisogram/secvisogram#446]
The REST api of csaf-cms-backend does not use trailing / when accessing elements, for example "/api/v1/advisories". Secvisogram partly uses trailing / as in "/api/v1/advisories/" resulting in "404" (not found) errors when trying to access the CSAF Documents in the backend system. The same holds true for "/api/v1/advisories/{id}/".

**Comment by tschmidtb51** [comment]
I guess this become necessary due to the change to Spring Boot 3 in https://github.com/secvisogram/csaf-cms-backend/pull/122/

**Comment by tschmidtb51** [comment]
Resolved with #447
