### ISSUE TITLE
Invalid Regexes in Input Pattern Attributes

### ISSUE THREAD

**Issue by pdamian** [secvisogram/secvisogram#47]
The pattern attribute in some input fields is incorrect.  Valid inputs are therefore highlighted with a red framing in Secvisogram's Form Editor.

Example `document.tracking.version`:
![image](https://user-images.githubusercontent.com/9308477/117253581-a2aba100-ae47-11eb-8b22-2c784f2d6fd8.png)

Corresponding input pattern:
`^(0|[1-9][0-9]*)$|^((0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*)(?:-((?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\\.(?:0|[1-9]\\d*|\\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\\+([0-9a-zA-Z-]+(?:\\.[0-9a-zA-Z-]+)*))?)$`

The problem seems to come from incorrect escaping. E.g. escaping the `.` character is incorrectly done by `\\.` but should be `\.`. Otherwise the `\` character is escaped (followed by `.` for a wildcard).

Correcting above regex, solves the problem:
`^(0|[1-9][0-9]*)$|^((0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?)$`

![image](https://user-images.githubusercontent.com/9308477/117253853-fa4a0c80-ae47-11eb-9f2a-d5de6700bd6b.png)

**Comment by tschmidtb51** [comment]
@pdamian: Do you have a suggestion how to fix the pURL pattern? Feel free to commit it into #49 or describe it here and I integrate it.
