### ISSUE TITLE
webeditor stuck at load when revison date is wrong

### ISSUE THREAD

**Issue by Heindl7** [secvisogram/secvisogram#524]
The secvisogram json editor stuck in "loading data" when a incorrect revision history is inserted
Steps to reproduce:
first start by inserting a valid revision history
```
"current_release_date": "2010-10-10T10:00:00.000Z",
      "id": "ABCDEF",
      "initial_release_date": "2010-10-10T10:00:00.000Z",
      "status": "final",
      "version": "1",
      "revision_history": [
        {
          "date": "2010-10-10T10:00:00.000Z",
          "number": "1",
          "summary": "initial"
        }
      ]
```
Then remove all "Z" from every date 
go to the "Form Editor" Tab
insert a new revision 
--> now you get the error:
Text '2010-10-10T10:00:00.000' could not be parsed at index 23: 2010-10-10T10:00:00.000, at index: 23

When you now try to go back to the "JSON Editor" the Webapp stuck in "Loading data..."

**Comment by tschmidtb51** [comment]
I guess the error occurs due to a check in background - but I'm not sure which one.
