### ISSUE TITLE
Investigate time mismatch

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#565]
We need to investigate, why the is a time mismatch between
```
      "current_release_date": "2024-04-08T00:00:00+00:00",
      "initial_release_date": "2024-02-08T00:00:00+01:00",
```
in the Form editor. There it shows as:
![grafik](https://github.com/secvisogram/secvisogram/assets/65305130/5c16fbb9-b65a-4cf6-a259-d42cd7e1095e)

which is weird. It looks like on converts it so local time (with DST) and the other want not.

**Comment by MarcoKorinth** [comment]
Investigation showed, that the two inputs behave the exact same way.
This behavior occurs with german timezone, which takes European summer/winter time into account.
In my opinion this behavior is correct.

**Comment by tschmidtb51** [comment]
You are right - I missed the daylight saving change :man_facepalming:
