### ISSUE TITLE
Update GHActions

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#587]
We need to update the GHActions. actions/upload-artifact@v3 should be replaced by https://github.com/PaloAltoNetworks/upload-secure-artifact (See https://unit42.paloaltonetworks.com/github-repo-artifacts-leak-tokens/). Also, use least privileges (see https://www.paloaltonetworks.com/blog/prisma-cloud/github-actions-opt-out-permissions-model/) in all actions.

**Comment by MarcoKorinth** [comment]
least privileges were applied to all actions.

upload-secure-artifact currently produces an docker error.
Also in my opinion this workflow isn't production ready without versioning. Currently it only supports @main which could break actions with updates

**Comment by tschmidtb51** [comment]
Thanks for checking
