### ISSUE TITLE
Last release broke Secvisogram

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#596]
The last release broke Secvisogram:

![grafik](https://github.com/user-attachments/assets/a4258e6d-71e8-4ba4-a063-7cf3671a01f8)

Now all captions and titles are missing. Please resolve this as soon as possible.

**Comment by StefanNemeth** [comment]
I cannot reproduce this issue. Checking out the most recent version (2.5.15) locally still displays all labels in both dev mode and the production build.

- What steps were you following when the issue occurred?
- What is your specific environment (browser, OS, running locally)?

**Comment by tschmidtb51** [comment]
I was running the GitHub version on Linux/Firefox. However, I reloaded just now and the issue is gone :shrug: 

So, I'm closing that - maybe it was a hick-up in the infrastructure :thinking: 

Thank you for looking into that so quickly.
