### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by tschmidtb51** [secvisogram/secvisogram#7]
oasis-tcs/csaf#194 sorts items alphabetically. This should be supported by Secvisogram.

**Comment by sthagen** [comment]
I think the merged PR #8 did solve this, didn‘t it?

**Comment by tschmidtb51** [comment]
> I think the merged PR #8 did solve this, didn‘t it?

Unfortuantely not. The JSON in CSAF Document should also be sorted alphabetically.

**Comment by tschmidtb51** [comment]
I have three things in mind:
1. The output in the tab `CSAF Document` is always sorted alphabetically.
2. Whenever the `JSON Editor` gets selected, the content is represented in alphabetical order so that whenever I add a field in the `Form Editor` it is automatically in the right place.
3. There should be an additional button in the tab `JSON Editor` that sorts the content of the editor alphabetically.

**Comment by tschmidtb51** [comment]
#219 solved the first item.

**Comment by tschmidtb51** [comment]
There is now an button, that sorts the document. So the third one is done.

**Comment by tschmidtb51** [comment]
The second one won't be implemented at the moment to avoid user confusion.
